const express=require("express"); const db=require("../db"); const {requireAuth}=require("../middleware/auth");
const router=express.Router(); router.use(requireAuth); const PERIODS=["weekly","monthly","yearly"];
function defaultPeriodBounds(periodType,anchor=new Date()){const d=new Date(anchor);if(periodType==="weekly"){const day=d.getDay()||7,start=new Date(d);start.setDate(d.getDate()-day+1);const end=new Date(start);end.setDate(start.getDate()+6);return[start.toISOString().slice(0,10),end.toISOString().slice(0,10)];}if(periodType==="monthly"){const start=new Date(d.getFullYear(),d.getMonth(),1),end=new Date(d.getFullYear(),d.getMonth()+1,0);return[start.toISOString().slice(0,10),end.toISOString().slice(0,10)];}const start=new Date(d.getFullYear(),0,1),end=new Date(d.getFullYear(),11,31);return[start.toISOString().slice(0,10),end.toISOString().slice(0,10)];}
router.get("/",async(req,res,next)=>{try{const{type}=req.query;let sql="SELECT * FROM goals WHERE user_id = ?",params=[req.userId];if(type&&PERIODS.includes(type)){sql+=" AND period_type = ?";params.push(type);}sql+=" ORDER BY period_start DESC, created_at DESC";res.json(await db.all(sql,...params));}catch(err){next(err);}});
router.post("/",async(req,res,next)=>{try{const{title,description,period_type,period_start,period_end,target_value,unit,linked_habit_id}=req.body||{};if(!title||!title.trim())return res.status(400).json({error:"A goal needs a title."});if(!PERIODS.includes(period_type))return res.status(400).json({error:"period_type must be weekly, monthly or yearly."});const[autoStart,autoEnd]=defaultPeriodBounds(period_type);const info=await db.run(`INSERT INTO goals (user_id,title,description,period_type,period_start,period_end,target_value,unit,linked_habit_id) VALUES (?,?,?,?,?,?,?,?,?) RETURNING id`,req.userId,title.trim(),description||"",period_type,period_start||autoStart,period_end||autoEnd,Number.isFinite(+target_value)?+target_value:100,unit||"%",linked_habit_id||null);res.status(201).json(await db.get("SELECT * FROM goals WHERE id = ?",info.lastInsertRowid));}catch(err){next(err);}});
router.patch("/:id/progress",async(req,res,next)=>{try{const goal=await db.get("SELECT * FROM goals WHERE id = ? AND user_id = ?",req.params.id,req.userId);if(!goal)return res.status(404).json({error:"Goal not found."});const{current_value,status}=req.body||{},newValue=Number.isFinite(+current_value)?+current_value:goal.current_value;let newStatus=["active","completed","missed"].includes(status)?status:goal.status;if(status===undefined&&newValue>=goal.target_value)newStatus="completed";await db.run(`UPDATE goals SET current_value=?,status=?,updated_at=datetime('now') WHERE id=?`,newValue,newStatus,goal.id);res.json(await db.get("SELECT * FROM goals WHERE id = ?",goal.id));}catch(err){next(err);}});
router.put("/:id",async(req,res,next)=>{try{const goal=await db.get("SELECT * FROM goals WHERE id = ? AND user_id = ?",req.params.id,req.userId);if(!goal)return res.status(404).json({error:"Goal not found."});const{title,description,target_value,unit,period_start,period_end}=req.body||{};await db.run(`UPDATE goals SET title=?,description=?,target_value=?,unit=?,period_start=?,period_end=?,updated_at=datetime('now') WHERE id=?`,title!==undefined&&title.trim()?title.trim():goal.title,description!==undefined?description:goal.description,Number.isFinite(+target_value)?+target_value:goal.target_value,unit||goal.unit,period_start||goal.period_start,period_end||goal.period_end,goal.id);res.json(await db.get("SELECT * FROM goals WHERE id = ?",goal.id));}catch(err){next(err);}});
router.delete("/:id",async(req,res,next)=>{try{const info=await db.run("DELETE FROM goals WHERE id = ? AND user_id = ?",req.params.id,req.userId);if(info.changes===0)return res.status(404).json({error:"Goal not found."});res.json({ok:true});}catch(err){next(err);}});
module.exports=router;
